baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Andrew Dallmann'
theme = ['hugo-embed-pdf-shortcode', 'gokarna']
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true

[params]
  footer = "-AD"
  description = ""
  avatarURL = "/images/pic.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/andrewdallmann/"},
    {name = "email", url = "mailto:example@example.com"}
  ]
  metaKeywords = ["pm", "product", "productmanagement"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Links"
    pre = "<span data-feather='book'></span>"
    url = "/links/"
    weight = 2

  [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='code'></span>"
    url = "/resume/"
    weight = 3

  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/andrewdallmann/"
    weight = 4

  [[menu.main]]
    identifier = "mail"
    pre = "<span data-feather='mail'></span>"
    url = "mailto:andrew.dallmann@gmail.com"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
